services:
    # spacy (ports: 812x)
    spacy-nl:
        image: ccl-kuleuven/taggers-dockerized-spacy:${VERSION}
        networks:
            - taggers-network
        environment:
            - CALLBACK_SERVER=${CALLBACK_SERVER}
            - SPACY_MODEL=nl_core_news_lg
        restart: unless-stopped
        ports:
            - 8120:8080

    spacy-en:
        image: ccl-kuleuven/taggers-dockerized-spacy:${VERSION}
        networks:
            - taggers-network
        environment:
            - CALLBACK_SERVER=${CALLBACK_SERVER}
            - SPACY_MODEL=en_core_web_lg
        restart: unless-stopped
        ports:
            - 8121:8080

    spacy-fr:
        image: ccl-kuleuven/taggers-dockerized-spacy:${VERSION}
        networks:
            - taggers-network
        environment:
            - CALLBACK_SERVER=${CALLBACK_SERVER}
            - SPACY_MODEL=fr_core_news_lg
        restart: unless-stopped
        ports:
            - 8122:8080

    spacy-de:
        image: ccl-kuleuven/taggers-dockerized-spacy:${VERSION}
        networks:
            - taggers-network
        environment:
            - CALLBACK_SERVER=${CALLBACK_SERVER}
            - SPACY_MODEL=de_core_news_lg
        restart: unless-stopped
        ports:
            - 8123:8080
    # LeTs (ports: 813x)
    lets-nl:
        image: ccl-kuleuven/taggers-dockerized-lets-nl:${VERSION}
        build:
            context: lets/base
        networks:
            - taggers-network
        environment:
            - LETS_LANG=nl
            - CALLBACK_SERVER=${CALLBACK_SERVER}
        restart: unless-stopped
        ports:
            - 8130:8080
    lets-fr:
        image: ccl-kuleuven/taggers-dockerized-lets-fr:${VERSION}
        build:
            context: lets/base
        networks:
            - taggers-network
        environment:
            - LETS_LANG=fr
            - CALLBACK_SERVER=${CALLBACK_SERVER}
        restart: unless-stopped
        ports:
            - 8131:8080
    lets-de:
        image: ccl-kuleuven/taggers-dockerized-lets-de:${VERSION}
        build:
            context: lets/base
        networks:
            - taggers-network
        environment:
            - LETS_LANG=de
            - CALLBACK_SERVER=${CALLBACK_SERVER}
        restart: unless-stopped
        ports:
            - 8132:8080
    lets-en:
        image: ccl-kuleuven/taggers-dockerized-lets-en:${VERSION}
        build:
            context: lets/base
        networks:
            - taggers-network
        environment:
            - LETS_LANG=en
            - CALLBACK_SERVER=${CALLBACK_SERVER}
        restart: unless-stopped
        ports:
            - 8133:8080

    # Lettuce (ports: 814x)
    lettuce-nl-mono:
        image: ccl-kuleuven/taggers-dockerized-lettuce:${VERSION}
        networks:
            - taggers-network
        environment:
            - HUGGINGFACE_MODEL=pranaydeeps/lettuce_pos_nl_mono
            - CALLBACK_SERVER=${CALLBACK_SERVER}
        restart: unless-stopped
        ports:
            - 8140:8080
    lettuce-nl-xlm:
        image: ccl-kuleuven/taggers-dockerized-lettuce:${VERSION}
        networks:
            - taggers-network
        environment:
            - HUGGINGFACE_MODEL=pranaydeeps/lettuce_pos_nl_xlm
            - CALLBACK_SERVER=${CALLBACK_SERVER}
        restart: unless-stopped
        ports:
            - 8141:8080
    lettuce-de-mono:
        image: ccl-kuleuven/taggers-dockerized-lettuce:${VERSION}
        build:
            context: huggingface/lettuce
        networks:
            - taggers-network
        environment:
            - HUGGINGFACE_MODEL=pranaydeeps/lettuce_pos_de_mono
            - CALLBACK_SERVER=${CALLBACK_SERVER}
        restart: unless-stopped
        ports:
            - 8142:8080
    lettuce-de-xlm:
        image: ccl-kuleuven/taggers-dockerized-lettuce:${VERSION}
        build:
            context: huggingface/lettuce
        networks:
            - taggers-network
        environment:
            - HUGGINGFACE_MODEL=pranaydeeps/lettuce_pos_de_xlm
            - CALLBACK_SERVER=${CALLBACK_SERVER}
        restart: unless-stopped
        ports:
            - 8143:8080
    lettuce-fr-mono:
        image: ccl-kuleuven/taggers-dockerized-lettuce:${VERSION}
        build:
            context: huggingface/lettuce
        networks:
            - taggers-network
        environment:
            - HUGGINGFACE_MODEL=pranaydeeps/lettuce_pos_fr_mono
            - CALLBACK_SERVER=${CALLBACK_SERVER}
        restart: unless-stopped
        ports:
            - 8144:8080
    lettuce-fr-xlm:
        image: ccl-kuleuven/taggers-dockerized-lettuce:${VERSION}
        build:
            context: huggingface/lettuce
        networks:
            - taggers-network
        environment:
            - HUGGINGFACE_MODEL=pranaydeeps/lettuce_pos_fr_xlm
            - CALLBACK_SERVER=${CALLBACK_SERVER}
        restart: unless-stopped
        ports:
            - 8145:8080

    lettuce-en-mono:
        image: ccl-kuleuven/taggers-dockerized-lettuce:${VERSION}
        build:
            context: huggingface/lettuce
        networks:
            - taggers-network
        environment:
            - HUGGINGFACE_MODEL=pranaydeeps/lettuce_pos_en_mono
            - CALLBACK_SERVER=${CALLBACK_SERVER}
        restart: unless-stopped
        ports:
            - 8146:8080
    lettuce-en-xlm:
        image: ccl-kuleuven/taggers-dockerized-lettuce:${VERSION}
        build:
            context: huggingface/lettuce
        networks:
            - taggers-network
        environment:
            - HUGGINGFACE_MODEL=pranaydeeps/lettuce_pos_en_xlm
            - CALLBACK_SERVER=${CALLBACK_SERVER}
        restart: unless-stopped
        ports:
            - 8147:8080

    # stanza (ports: 819x)
    stanza-nl:
        image: ccl-kuleuven/taggers-dockerized-stanza:${VERSION}
        restart: unless-stopped
        environment:
            - STANZA_LANG=nl
            - CALLBACK_SERVER=${CALLBACK_SERVER}
        ports:
            - 8190:8080
    stanza-en:
        image: ccl-kuleuven/taggers-dockerized-stanza:${VERSION}
        restart: unless-stopped
        environment:
            - STANZA_LANG=en
            - CALLBACK_SERVER=${CALLBACK_SERVER}
        ports:
            - 8191:8080
    stanza-fr:
        image: ccl-kuleuven/taggers-dockerized-stanza:${VERSION}
        restart: unless-stopped
        environment:
            - STANZA_LANG=fr
            - CALLBACK_SERVER=${CALLBACK_SERVER}
        ports:
            - 8192:8080
    stanza-de:
        image: ccl-kuleuven/taggers-dockerized-stanza:${VERSION}
        restart: unless-stopped
        environment:
            - STANZA_LANG=de
            - CALLBACK_SERVER=${CALLBACK_SERVER}
        ports:
            - 8193:8080
networks:
    taggers-network:
        # external applications can attach to this network to access the taggers 
        driver: bridge
